# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HSV sliders.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(655, 285)
        self.Hue_min_slider = QtWidgets.QSlider(Form)
        self.Hue_min_slider.setGeometry(QtCore.QRect(80, 30, 491, 22))
        self.Hue_min_slider.setMaximum(180)
        self.Hue_min_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Hue_min_slider.setObjectName("Hue_min_slider")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 30, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Hue_min = QtWidgets.QPlainTextEdit(Form)
        self.Hue_min.setGeometry(QtCore.QRect(590, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hue_min.setFont(font)
        self.Hue_min.setObjectName("Hue_min")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Hue_max_slider = QtWidgets.QSlider(Form)
        self.Hue_max_slider.setGeometry(QtCore.QRect(80, 60, 491, 22))
        self.Hue_max_slider.setMaximum(180)
        self.Hue_max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Hue_max_slider.setObjectName("Hue_max_slider")
        self.Sat_min_slider = QtWidgets.QSlider(Form)
        self.Sat_min_slider.setGeometry(QtCore.QRect(80, 90, 491, 22))
        self.Sat_min_slider.setMaximum(255)
        self.Sat_min_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Sat_min_slider.setObjectName("Sat_min_slider")
        self.Sat_max_slider = QtWidgets.QSlider(Form)
        self.Sat_max_slider.setGeometry(QtCore.QRect(80, 120, 491, 22))
        self.Sat_max_slider.setMaximum(255)
        self.Sat_max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Sat_max_slider.setObjectName("Sat_max_slider")
        self.Val_min_slider = QtWidgets.QSlider(Form)
        self.Val_min_slider.setGeometry(QtCore.QRect(80, 150, 491, 22))
        self.Val_min_slider.setMaximum(255)
        self.Val_min_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Val_min_slider.setObjectName("Val_min_slider")
        self.Val_max_slider = QtWidgets.QSlider(Form)
        self.Val_max_slider.setGeometry(QtCore.QRect(80, 180, 491, 22))
        self.Val_max_slider.setMaximum(255)
        self.Val_max_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Val_max_slider.setObjectName("Val_max_slider")
        self.Hue_max = QtWidgets.QPlainTextEdit(Form)
        self.Hue_max.setGeometry(QtCore.QRect(590, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Hue_max.setFont(font)
        self.Hue_max.setObjectName("Hue_max")
        self.Sat_min = QtWidgets.QPlainTextEdit(Form)
        self.Sat_min.setGeometry(QtCore.QRect(590, 80, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Sat_min.setFont(font)
        self.Sat_min.setObjectName("Sat_min")
        self.Sat_max = QtWidgets.QPlainTextEdit(Form)
        self.Sat_max.setGeometry(QtCore.QRect(590, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Sat_max.setFont(font)
        self.Sat_max.setObjectName("Sat_max")
        self.Val_min = QtWidgets.QPlainTextEdit(Form)
        self.Val_min.setGeometry(QtCore.QRect(590, 140, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Val_min.setFont(font)
        self.Val_min.setObjectName("Val_min")
        self.Val_max = QtWidgets.QPlainTextEdit(Form)
        self.Val_max.setGeometry(QtCore.QRect(590, 170, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Val_max.setFont(font)
        self.Val_max.setObjectName("Val_max")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.Size_slier = QtWidgets.QSlider(Form)
        self.Size_slier.setGeometry(QtCore.QRect(80, 210, 491, 22))
        self.Size_slier.setMaximum(5000)
        self.Size_slier.setOrientation(QtCore.Qt.Horizontal)
        self.Size_slier.setObjectName("Size_slier")
        self.Size = QtWidgets.QPlainTextEdit(Form)
        self.Size.setGeometry(QtCore.QRect(590, 200, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Size.setFont(font)
        self.Size.setObjectName("Size")
        self.exitButton = QtWidgets.QPushButton(Form)
        self.exitButton.setGeometry(QtCore.QRect(10, 250, 75, 23))
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(Form)
        self.Hue_max.windowIconTextChanged['QString'].connect(Form.update)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Hue Min"))
        self.label_2.setText(_translate("Form", "Hue Max"))
        self.label_3.setText(_translate("Form", "Sat Min"))
        self.label_4.setText(_translate("Form", "Sat Max"))
        self.label_5.setText(_translate("Form", "Val Min"))
        self.label_6.setText(_translate("Form", "Val Max"))
        self.label_7.setText(_translate("Form", "Size"))
        self.exitButton.setText(_translate("Form", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
